Makefile
config/redirects
worker.sh

JIRA: https://jira.mongodb.org/browse/DOCSP-8994
- Update `redirects` to point to latest versions
- Update `Makefile`
No staging (not supported by autobuilder yet)

Docsp 8994 update php version

---

config/integration.yaml
config/redirects

JIRA:
https://jira.mongodb.org/browse/DOCS-10188
- Added v1.7 (stable remains 1.6) and associated redirects
- Removed base/links entries since they are no longer used

DOCSP-10188: add v1.7 branch

---

config/build_conf.yaml

JIRA:
https://jira.mongodb.org/browse/DOCSP-11548
Staging:
https://docs-mongodbcom-staging.corp.mongodb.com/php-library/ccho/DOCSP-11542-update-v1.7-conf/reference/class/MongoDBCollection.html#phpclass.MongoDB\Collection
From some experimentation, it looks like config/build_conf.yaml contains an entry for version that needed to be updated for your v1.7 branch.

DOCSP-11542: Update version in build_conf to correct title

---

config/build_conf.yaml

JIRA:
https://jira.mongodb.org/browse/DOCSP-11548
Staging:
https://docs-mongodborg-staging.corp.mongodb.com/php-library/ccho/DOCSP-11548-version-label/index.html

DOCSP-11548: update page title label to 1.8-dev for master branch

---

Makefile

@terakilobyte This will shift the PHP docs to live in a DOP-owned AWS bucket rather than the monolithic and ancient 10gen-noc. We'll need this Makefile change backported to all of the phplib branches; if y'all could handle the cherry-picking and rebuilding, that would be ideal.
Guru should have already sent updated AWS credentials to use with Giza via 0bin.

Update Makefile to point to DOP-owned AWS buckets

---

config/redirects

JIRA: https://jira.mongodb.org/browse/DOCSP-20867
Output:
```sh
❯ mut-redirects config/redirects
Redirect 301 /php-library/ https://docs.mongodb.com/php-library/current
Redirect 301 /php-library/v1.9/tutorials/versioned-api/ https://docs.mongodb.com/php-library/v1.9/tutorials/stable-api/
Redirect 301 /php-library/v1.10/tutorials/versioned-api/ https://docs.mongodb.com/php-library/v1.10/tutorials/stable-api/
Redirect 301 /php-library/master/tutorials/versioned-api/ https://docs.mongodb.com/php-library/master/tutorials/stable-api/
```

DOCSP-20867: update redirects for versioned api and 1.10

---

Makefile

Need to ensure that the "source/" path exists for the rsync command executed when using one of the make targets that depends on it. If it doesn't exist, the build will fail with an error that looks like the following:
```
giza make html
INFO:giza.operations.make:running sphinx build operation, equivalent to: giza sphinx --builder html
INFO:giza.content.assets:updated /Users/.../dev/docs-php-library/build/docs-tools repository
rsync: link_stat "/Users/.../dev/docs-php-library/source/." failed: No such file or directory (2)
rsync error: some files could not be transferred (code 23) at /AppleInternal/Library/BuildRoots/a0876c02-1788-11ed-b9c4-96898e02b808/Library/Caches/com.apple.xbs/Sources/rsync/rsync/main.c(996) [sender=2.6.9]
ERROR:giza.content.source:source transfer rsync had error: 23 …
```

Update the Makefile target to add the source/ directory if it doesn't exist already

---

.gitmodules

JIRA - https://jira.mongodb.org/browse/DOCSP-37038
Staging - https://preview-mongodbnorareidy.gatsbyjs.io/php-library/DOCSP-37038/
Output from git submodule status:
` 280f20c37e1c55afe870e3259d5a13b05287aa53 mongo-php-library (1.17.0-55-g280f20c3)`
Output from git log on mongo-php-library:
```
commit 280f20c37e1c55afe870e3259d5a13b05287aa53 (HEAD -> master, upstream/master, origin/master, origin/HEAD)
Merge: 00d44d41 12ba7124
Author: Jeremy Mikola <jmikola@gmail.com>
Date:   Wed Feb 21 15:42:15 2024 -0500
Merge branch 'v1.17'
commit 12ba7124f1cf1e3e32a374772eeccb65756388d1
Author: Nora Reidy <nora.reidy@mongodb.com>
Date:   Wed Feb 21 15:41:56 2024 -0500
DOCSP-37038: Fix broken links (#1233)
```

DOCSP-37038: Fix links (staging)

---

config/redirects

JIRA: https://jira.mongodb.org/browse/DOCSP-37915
Added redirect:
```
Redirect 301 /docs/php-library/v1.16/tutorial/encryption/ https://www.mongodb.com/docs/php-library/v1.16/
```

DOCSP-37915: add redirect from in-use encryption for 1.16

---

snooty.toml

This JIRA ticket identifies the PHP Functions page as having very little text. This PR makes it a drawer only, rather than a landing page.
JIRA: https://jira.mongodb.org/browse/DOCSP-38363
Staging: https://preview-mongodbmongokart.gatsbyjs.io/php-library/docsp-38363-delist-functions/reference/function/add_logger/

DOCSP-38363 - Make Functions a drawer only

---

.gitmodules
README.rst
snooty.toml

https://jira.mongodb.org/browse/DOCSP-41495
adds information about server compat updates
[staging](https://preview-mongodbrustagir.gatsbyjs.io/php-library/DOCSP-41495-php-server-eol/whats-new/)
[content PR](https://github.com/mongodb/mongo-php-library/pull/1364)

DOCSP-41495: php v1.20 compat updates

---

source/get-started.txt
source/get-started/create-a-deployment.txt
source/includes/get-started/troubleshoot.rst
source/index.txt

JIRA - https://jira.mongodb.org/browse/DOCSP-41953
Staging - https://preview-mongodbnorareidy.gatsbyjs.io/php-library/DOCSP-41953-mongodb-deployment/get-started/create-a-deployment/

DOCSP-41953: Create a deployment

---

source/get-started.txt
source/get-started/next-steps.txt

JIRA - https://jira.mongodb.org/browse/DOCSP-42388
Staging - https://preview-mongodbnorareidy.gatsbyjs.io/php-library/DOCSP-42388-next-steps/get-started/next-steps/

DOCSP-42388: Next steps

---

.github/actions/setup/action.yml
.github/workflows/coding-standards.yml
.github/workflows/static-analysis.yml
.gitignore
composer.json
phpcs.xml
psalm-baseline.xml
psalm.xml
source/examples/codecs/handling-embedded-documents/Person.php

JIRA - <https://jira.mongodb.org/browse/DOCSP-42819>
Adapted the actions from the source driver repo but changed the rules for when the action should be run and on which filetypes

DOCSP-42819: add coding standards workflow

---

source/includes/read/change-streams.php
source/read.txt
source/read/change-streams.txt

JIRA - https://jira.mongodb.org/browse/DOCSP-41981
Staging - https://preview-mongodbnorareidy.gatsbyjs.io/php-library/DOCSP-41981-change-streams/read/change-streams/

DOCSP-41981: Change streams

---

snooty.toml
source/includes/write/insert.php
source/index.txt
source/write.txt
source/write/insert.txt

JIRA - https://jira.mongodb.org/browse/DOCSP-41967
Staging - https://preview-mongodbnorareidy.gatsbyjs.io/php-library/DOCSP-41967-insert/write/insert/

DOCSP-41967: Insert documents

---

source/aggregation.txt
source/includes/aggregation.php
source/includes/read/limit-skip-sort.php
source/includes/read/project.php
source/includes/read/retrieve.php
source/includes/read/specify-queries.php
source/index.txt

JIRA - https://jira.mongodb.org/browse/DOCSP-41988
Staging - https://preview-mongodbnorareidy.gatsbyjs.io/php-library/DOCSP-41988-aggregation/aggregation/

DOCSP-41988: Aggregation

---

source/includes/write/delete.php
source/write.txt
source/write/delete.txt

JIRA - https://jira.mongodb.org/browse/DOCSP-41970
Staging - https://preview-mongodbnorareidy.gatsbyjs.io/php-library/DOCSP-41970-delete/write/delete/

DOCSP-41970: Delete documents

---

source/includes/usage-examples/index-code-examples.php
source/includes/usage-examples/sample-app-intro.rst
source/includes/usage-examples/sample-app.php
source/index.txt
source/indexes.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-41983>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/php-library/DOCSP-41983-indexes-landing/indexes/

DOCSP-41983: indexes landing pg

---

source/includes/indexes/indexes.php
source/indexes.txt
source/indexes/index-mgmt.txt
source/indexes/single-field-index.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-41984>
Staging:
- [index mgmt](https://preview-mongodbrustagir.gatsbyjs.io/php-library/DOCSP-41984-single-fld-idx/indexes/index-mgmt/)
- [single field indexes](https://preview-mongodbrustagir.gatsbyjs.io/php-library/DOCSP-41984-single-fld-idx/indexes/single-field-index/)

DOCSP-41984: single field index

---

source/includes/indexes/indexes.php
source/includes/usage-examples/index-code-examples.php
source/indexes.txt
source/indexes/index-mgmt.txt
source/indexes/multikey-index.txt
source/indexes/single-field-index.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-41986>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/php-library/DOCSP-41986-multikey-indexes/indexes/multikey-index/

DOCSP-41986: multikey indexes

---

snooty.toml
source/includes/usage-examples/write-code-examples.php
source/write.txt

JIRA - https://jira.mongodb.org/browse/DOCSP-41966
Staging - https://deploy-preview-135--docs-php-library.netlify.app/write/

DOCSP-41966: Write operations landing

---

source/index.txt
source/security.txt
source/security/in-use-encryption.txt

Mostly identical to the [C++ In-Use Encryption](https://www.mongodb.com/docs/languages/cpp/cpp-driver/upcoming/security/in-use-encryption/) page
JIRA - https://jira.mongodb.org/browse/DOCSP-42026
Staging - https://deploy-preview-142--docs-php-library.netlify.app/security/in-use-encryption/

DOCSP-42026: In use encryption

---

source/includes/indexes/indexes.php
source/indexes.txt
source/indexes/compound-index.txt
source/indexes/index-mgmt.txt
source/indexes/single-field-index.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-41985>
Staging - https://deploy-preview-141--docs-php-library.netlify.app/indexes/compound-index/

DOCSP-41985: compound idx

---

source/databases-collections.txt
source/includes/databases-collections/databases-collections.php
source/index.txt

JIRA - https://jira.mongodb.org/browse/DOCSP-41963
Staging - https://deploy-preview-136--docs-php-library.netlify.app/databases-collections/

DOCSP-41963: Databases and collections

---

snooty.toml
source/includes/indexes/indexes.php
source/indexes.txt
source/indexes/atlas-search-index.txt
source/indexes/index-mgmt.txt
source/indexes/single-field-index.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-41987>
Staging - https://deploy-preview-143--docs-php-library.netlify.app/indexes/atlas-search-index/

DOCSP-41987: atlas search idx

---

source/monitoring/cluster-monitoring.txt

After [DOCSP-41982](https://jira.mongodb.org/browse/DOCSP-41982) was completed, I opened [PHPC-2449](https://jira.mongodb.org/browse/PHPC-2449) to improve the PHP.net docs. While doing so, I realized the original descriptions for these events were inaccurate.
This is based on changes in https://github.com/php/doc-en/pull/3802
Note that there are additional caveats for the topology open/closed events (the driver's client persistence behavior may get in the way of observing them), but I don't think we need to discuss that in this tutorial.

Revise descriptions for server opening/closed events

---

snooty.toml
source/index.txt
source/upgrade.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-41992>
Staging - <https://deploy-preview-152--docs-php-library.netlify.app/upgrade/>

DOCSP-41992 Upgrade versions

---

config/redirects

adds redirects in both directions
mut redirects:
```
Redirect 301 /docs/php-library/ https://www.mongodb.com/docs/php-library/current
Redirect 301 /docs/php-library/v1.17/tutorial/client-side-encryption/ https://www.mongodb.com/docs/php-library/v1.17/tutorial/encryption/
Redirect 301 /docs/php-library/v1.18/tutorial/client-side-encryption/ https://www.mongodb.com/docs/php-library/v1.18/tutorial/encryption/
Redirect 301 /docs/php-library/v1.19/tutorial/client-side-encryption/ https://www.mongodb.com/docs/php-library/v1.19/tutorial/encryption/
Redirect 301 /docs/php-library/v1.16/tutorial/encryption/ https://www.mongodb.com/docs/php-library/v1.16/
Redirect 301 /docs/php-library/v1.20/tutorial/install-php-library/ https://www.mongodb.com/docs/php-library/v1.20/get-started …
```

Implement redirects for standardized docs

---

source/tutorial.txt
source/whats-new.txt

Staging - https://deploy-preview-159--docs-php-library.netlify.app/whats-new/#what-s-new-in-1.20

adds more info to v1.20 whats new

---

source/reference/method/MongoDBDatabase-selectGridFSBucket.txt
source/reference/method/MongoDBGridFSBucket-openUploadStream.txt
source/reference/method/MongoDBGridFSBucket-uploadFromStream.txt
source/reference/method/MongoDBGridFSBucket__construct.txt
source/whats-new.txt
source/write/gridfs.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-43668>
Staging - https://deploy-preview-164--docs-php-library.netlify.app/whats-new/

DOCSP-43668: v2 removal of gridfs fields

---

source/whats-new.txt

v1.16 has reached it's end-of-life per the archival policy (linked in Epic). Release notes for this version and all earlier versions should also be removed from current versions (v1.17 and later). This preserves the changelog information in the original versions (e.g. v1.15 notes are in the v1.15 changelog, but not later versions).
JIRA - <https://jira.mongodb.org/browse/DOCSP-44298>
Staging - <https://deploy-preview-165--docs-php-library.netlify.app/whats-new/>

(DOCSP-44298) [PHP Library]: update changelogs to remove updates for EOL'd versions v1.16 & earlier

---

source/reference/method/MongoDBDatabase-createCollection.txt
source/whats-new.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-44238>
Staging - https://deploy-preview-171--docs-php-library.netlify.app/whats-new/#what-s-new-in-2.0

DOCSP-44238: v2 remove autoindex

---

source/includes/extracts-note.yaml

JIRA - <https://jira.mongodb.org/browse/DOCSP-44610>
Staging - https://deploy-preview-175--docs-php-library.netlify.app/reference/method/MongoDBCollection-count/#behavior

DOCSP-44610: fix php bson link

---

source/reference/function/with_transaction.txt
source/reference/method/MongoDBClient-listDatabaseNames.txt
source/reference/method/MongoDBClient-listDatabases.txt
source/reference/method/MongoDBClient__construct.txt
source/reference/method/MongoDBCollection-listIndexes.txt
source/reference/method/MongoDBDatabase-listCollectionNames.txt
source/reference/method/MongoDBDatabase-listCollections.txt
source/tutorial/server-selection.txt

Change specifications links to Markdown files

---

source/connect.txt
source/data-formats.txt
source/databases-collections.txt
source/get-started.txt
source/index.txt
source/indexes.txt
source/monitoring.txt
source/read.txt
source/reference.txt
source/reference/result-classes.txt
source/security.txt
source/write.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-44903>
Staging - <https://deploy-preview-176--docs-php-library.netlify.app/>
Current TOC: https://www.mongodb.com/docs/php-library/current/

DOCSP-44903 Shorten TOC Labels

---

source/faq.txt

JIRA - https://jira.mongodb.org/browse/PHPLIB-1278
Staging - https://deploy-preview-178--docs-php-library.netlify.app/faq/#connection-handling-and-persistence

PHPLIB-1278: Add FAQ about manually closing connections with disableClientPersistence

---

source/reference/method/MongoDBDatabase-createCollection.txt

No changes to content except denesting nested admonitions.
Build log has a temporary buildhooks error which are nonblocking per DOP, see Slack conversation verifying this: https://mongodb.slack.com/archives/C018UTGP23T/p1733237894795969
JIRA - https://jira.mongodb.org/browse/DOCSP-45749
Staging -

(DOCSP-45749) Denests last phase 1 nested components

---

source/includes/write/gridfs.php
source/write/gridfs.txt

JIRA - https://jira.mongodb.org/browse/DOCSP-45100
Staging - https://deploy-preview-187--docs-php-library.netlify.app/write/gridfs/

DOCSP-45100: Delete and rename by name

---

source/includes/write/gridfs.php
source/read/distinct.txt
source/write/gridfs.txt

JIRA - https://jira.mongodb.org/browse/DOCSP-45100, https://jira.mongodb.org/browse/DOCSP-45139
Staging - https://deploy-preview-190--docs-php-library.netlify.app/write/gridfs/
https://deploy-preview-190--docs-php-library.netlify.app/read/distinct/

Revert v1.21 changes

---

.github/workflows/vale-tdbx.yml
source/reference/class/MongoDBClient.txt
source/reference/class/MongoDBCollection.txt
source/reference/class/MongoDBDatabase.txt
source/reference/method/MongoDBClient-getCollection.txt
source/reference/method/MongoDBClient-getDatabase.txt
source/reference/method/MongoDBDatabase-getCollection.txt
source/reference/method/MongoDBDatabase-selectCollection.txt
source/whats-new.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-44644>
Staging:

DOCSP-44644: db/coll accessor methods

---

source/includes/extracts-note.yaml
source/includes/indexes/indexes.php
source/indexes.txt
source/indexes/atlas-search-index.txt
source/reference/method/MongoDBCollection-createIndexes.txt
source/reference/method/MongoDBCollection-createSearchIndex.txt
source/reference/method/MongoDBCollection-createSearchIndexes.txt
source/whats-new.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-43365>
Staging:
1. [indexes guide](https://deploy-preview-199--docs-php-library.netlify.app/indexes/atlas-search-index/)
2. [createSearchIndex api](https://deploy-preview-199--docs-php-library.netlify.app/reference/method/MongoDBCollection-createSearchIndex/)
3. [createSearchIndexes api](https://deploy-preview-199--docs-php-library.netlify.app/reference/method/MongoDBCollection-createSearchIndexes/)
4. [whats new](https://deploy-preview-199--docs-php-library.netlify.app/whats-new/#what-s-new-in-1.20)
**backports back to v1.20**

DOCSP-43365: type specification for createSearchIndex(es)

---

source/reference/method/MongoDBDatabase-createCollection.txt
source/whats-new.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-44237>
Staging - <https://deploy-preview-201--docs-php-library.netlify.app/reference/method/MongoDBDatabase-createCollection/#:~:text=version%201.9.-,flags,-integer>

DOCSP-44237 flags Option deprecation on v2.21

---

.github/workflows/coding-standards.yml
.github/workflows/static-analysis.yml
snooty.toml
source/aggregation.txt
source/aggregation/atlas-search.txt
source/aggregation/vector-search.txt
source/includes/aggregation/aggregation.php
source/indexes/atlas-search-index.txt
source/whats-new.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-43919>
Staging - 
1. [agg page](https://deploy-preview-203--docs-php-library.netlify.app/aggregation/)
2. [whats new](https://deploy-preview-203--docs-php-library.netlify.app/whats-new/#what-s-new-in-1.21)

DOCSP-43919: aggregation builder

---

source/reference/method/MongoDBCollection-bulkWrite.txt
source/reference/method/MongoDBCollection-replaceOne.txt
source/reference/method/MongoDBCollection-updateOne.txt
source/whats-new.txt
source/write/replace.txt
source/write/update.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-47864>
Staging - 
https://deploy-preview-209--docs-php-library.netlify.app/reference/method/MongoDBCollection-updateOne/#parameters
https://deploy-preview-209--docs-php-library.netlify.app/reference/method/MongoDBCollection-replaceOne/#parameters
https://deploy-preview-209--docs-php-library.netlify.app/whats-new/#std-label-php-lib-version-1.21

DOCSP-47864: sort order for updateone / replaceone

---

source/aggregation.txt
source/builders.txt
source/includes/builders.php
source/index.txt
source/read/change-streams.txt
source/read/specify-a-query.txt
source/write/transaction.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-43464>
Staging - https://deploy-preview-206--docs-php-library.netlify.app/builders/

DOCSP-43464: operations with builders

---

source/index.txt
source/read.txt

[PHP] Remove "MongoDB" from page title
(cherry picked from commit 97960e1e63884908040f238e45db3385c3c2eb3c)
JIRA - https://jira.mongodb.org/browse/DOCSP-48025
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/NNNNN/>
From https://github.com/mongodb/docs-php-library/pull/218

[PHP] Backport title change to v1.20

---

source/aggregation.txt
source/aggregation/atlas-search.txt
source/aggregation/vector-search.txt
source/includes/aggregation/aggregation.php
source/includes/aggregation/atlas-search.php
source/includes/aggregation/vector-search.php
source/read/cursor.txt
source/reference/method/MongoDBCollection-aggregate.txt
source/reference/method/MongoDBDatabase-aggregate.txt
source/whats-new.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-47217>
Staging:
1. [whats new](https://deploy-preview-217--docs-php-library.netlify.app/whats-new/#what-s-new-in-2.0)
2. agg api doc [db](https://deploy-preview-217--docs-php-library.netlify.app/reference/method/MongoDBDatabase-aggregate/) | [coll](https://deploy-preview-217--docs-php-library.netlify.app/reference/method/MongoDBCollection-aggregate/)
3. [agg page](https://deploy-preview-217--docs-php-library.netlify.app/aggregation/#aggregation-builder)
4. [vector search examples](https://deploy-preview-217--docs-php-library.netlify.app/aggregation/vector-search/#atlas-search-query-examples)
5. [atlas search …

DOCSP-47217: pipeline param

---

source/includes/extracts-watch-option.yaml
source/read/retrieve.txt
source/reference/method/MongoDBCollection-find.txt
source/reference/method/MongoDBCollection-listSearchIndexes.txt
source/reference/method/MongoDBDatabase-aggregate.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-47835>
Staging - <https://deploy-preview-215--docs-php-library.netlify.app/reference/method/MongoDBCollection-listSearchIndexes/#parameters>
<https://deploy-preview-215--docs-php-library.netlify.app/reference/method/MongoDBDatabase-aggregate/#parameters>
<https://deploy-preview-215--docs-php-library.netlify.app/reference/method/MongoDBCollection-find/#parameters>
<https://deploy-preview-215--docs-php-library.netlify.app/reference/method/MongoDBDatabase-watch/#parameters>
<https://deploy-preview-215--docs-php-library.netlify.app/read/retrieve/#modify-find-behavior>
Note: This topic is a bit over my head in terms of technicalities of the batchsize …

DOCSP-47835 Clarify batchsize behavior

---

composer/composer.json
snooty.toml
source/includes/extracts-bulkwriteexception.yaml
source/includes/extracts-error.yaml
source/includes/write/bulk-write.php
source/reference.txt
source/reference/class/MongoDBBulkWriteCommandResult.txt
source/reference/class/MongoDBBulkWriteResult.txt
source/reference/class/MongoDBClient.txt
source/reference/class/MongoDBClientBulkWrite.txt
source/reference/method/MongoDBClient-bulkWrite.txt
source/reference/method/MongoDBClientBulkWrite-createWithCollection.txt
source/reference/method/MongoDBClientBulkWrite-deleteMany.txt
source/reference/method/MongoDBClientBulkWrite-deleteOne.txt
source/reference/method/MongoDBClientBulkWrite-insertOne.txt
source/reference/method/MongoDBClientBulkWrite-replaceOne.txt
source/reference/method/MongoDBClientBulkWrite-updateMany.txt
source/reference/method/MongoDBClientBulkWrite-updateOne.txt
source/reference/method/MongoDBClientBulkWrite-withCollection.txt
source/reference/method/MongoDBCollection-bulkWrite.txt
source/reference/method/MongoDBCollection-insertMany.txt
source/reference/result-classes.txt
source/whats-new.txt
source/write/bulk-write.txt
source/write/replace.txt
source/write/transaction.txt
source/write/update.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-49150>
<li><a href=https://deploy-preview-250--docs-php-library.netlify.app/reference/class/MongoDBBulkWriteCommandResult>reference/class/MongoDBBulkWriteCommandResult</a></li><li><a href=https://deploy-preview-250--docs-php-library.netlify.app/reference/class/MongoDBClientBulkWrite>reference/class/MongoDBClientBulkWrite</a></li><li><a href=https://deploy-preview-250--docs-php-library.netlify.app/reference/method/MongoDBClient-bulkWrite>reference/method/MongoDBClient-bulkWrite</a></li><li><a href=https://deploy-preview-250--docs-php-library.netlify.app/reference/method/MongoDBClientBulkWrite-createWithCollection>reference/method/MongoDBClientBulkWrit …

DOCSP-49150: bulkWrite docs + api

---

source/includes/mongodb-compatibility-table-php.rst
source/whats-new.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-50155>
<li><a href=https://deploy-preview-252--docs-php-library.netlify.app/whats-new>whats-new</a></li>
- [compat](https://deploy-preview-252--docs-php-library.netlify.app/compatibility/)

DOCSP-50155 - EOL MongoDB 4.0

---

snooty.toml
source/includes/language-compatibility-table-php.rst
source/whats-new.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-50294>
<li><a href=https://deploy-preview-255--docs-php-library.netlify.app/whats-new>whats-new</a></li>

DOCSP-50294: v2.1 release

---

source/includes/usage-examples/write-code-examples.php
source/write.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-50301>
<li><a href=https://deploy-preview-259--docs-php-library.netlify.app/write>write</a></li>

DOCSP-50301: use client bw in write landing pg

---

source/connect/connection-options.txt
source/crud/read-write-pref.txt

JIRA - https://jira.mongodb.org/browse/DOCSP-47065
<li><a href=https://deploy-preview-257--docs-php-library.netlify.app/connect/connection-options>connect/connection-options</a></li><li><a href=https://deploy-preview-257--docs-php-library.netlify.app/crud/read-write-pref>crud/read-write-pref</a></li>

DOCSP-47065: Load balancing

---

source/data-formats.txt
source/data-formats/extended-json.txt
source/includes/extended-json.php

JIRA - https://jira.mongodb.org/browse/DOCSP-47071
<li><a href=https://deploy-preview-268--docs-php-library.netlify.app/data-formats/extended-json>data-formats/extended-json</a></li><li><a href=https://deploy-preview-268--docs-php-library.netlify.app/data-formats>data-formats</a></li>

DOCSP-47071: Extended JSON

---

source/aggregation.txt

JIRA - <https://jira.mongodb.org/browse/DOCSP-50753>
<li><a href=https://deploy-preview-275--docs-php-library.netlify.app/aggregation>aggregation</a></li>

DOCSP-50753: agg tutorial link

---

source/connect.txt
source/connect/connection-options.txt
source/connect/connection-troubleshooting.txt

JIRA - https://jira.mongodb.org/browse/DOCSP-50185
This PR uses the copy from the [shared Connection Troubleshooting page](https://github.com/10gen/docs-shared/blob/main/dbx/connection-troubleshooting.rst) but removes information about connection pooling, which the PHP library does not support.
<li><a href=https://deploy-preview-272--docs-php-library.netlify.app/connect/connection-troubleshooting>connect/connection-troubleshooting</a></li><li><a href=https://deploy-preview-272--docs-php-library.netlify.app/connect>connect</a></li><li><a href=https://deploy-preview-272--docs-php-library.netlify.app/connect/connection-options>connect/connection-options</a></li>

DOCSP-50185: Connection troubleshooting
