- conf.py
https://jira.mongodb.org/browse/DRIVERS-409
> DRIVERS-409: Update copyright blurb

- config/redirects
Update redirects file to point current to 1.7
> update redirects file for 1.7

- config/build_conf.yaml
- config/redirects
JIRA:
https://jira.mongodb.org/browse/DOCSP-13908
No preview (not nextgen)
> DOCSP-13908: configuration updates for version 1.8

- config/build_conf.yaml
JIRA:
https://jira.mongodb.org/browse/DOCSP-13908
Necessary changes to create v1.8 branch for deployment (old gen)
> v1.8 branch

- config/build_conf.yaml
Reverts mongodb/docs-php-library#20
> Revert "v1.8 branch"

- config/build_conf.yaml
- config/redirects
> bump for v1.9 cut

- config/redirects
> update master for new version

- config/redirects
[PR Reviewing Guidelines](https://github.com/mongodb/docs-ecosystem/blob/master/REVIEWING.md)
JIRA - <https://jira.mongodb.org/browse/DOCSP-26681>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/DOCSP-26681-php-version-updates-1.15/php/>
> DOCSP-26681 PHP Version Updates (redirects)

- config/redirects
(cherry picked from commit c546f8eb50147f434c8d14a0ebdd6522a283d6d6)
> DOCSP-26681 v1.15 update redirects

- conf.py
> DOCSP-30856: v1.11 EOL

- conf.py
> DOCSP-30856: v1.10 EOL

- conf.py
> DOCSP-30856: v1.2 EOL

- conf.py
> DOCSP-30856: v1.3 EOL

- conf.py
> DOCSP-30856: v1.6 EOL

- conf.py
> DOCSP-30856: v1.9 EOL

- conf.py
> DOCSP-30856: v1.8 EOL

- conf.py
> DOCSP-30856: v1.5 EOL

- conf.py
> DOCSP-30856: v1.4 EOL

- config/redirects
JIRA: https://jira.mongodb.org/browse/DOCSP-31241
```
» mut-redirects config/redirects
Redirect 301 /docs/php-library/ https://www.mongodb.com/docs/php-library/current
Redirect 301 /docs/php-library/master/tutorial/client-side-encryption/ https://www.mongodb.com/docs/php-library/master/tutorial/encryption/
```
> DOCSP-31241: CSFLE tutorial redirect

- snooty.toml
- worker.sh
JIRA: https://jira.mongodb.org/browse/DOCSP-35780
Compare with the following files on the master branch:
- [snooty.toml](https://github.com/mongodb/docs-php-library/blob/master/snooty.toml)
- [worker.sh](https://github.com/mongodb/docs-php-library/blob/master/worker.sh)
> DOCSP-35780: enable snooty build

- .gitmodules
- snooty.toml
This PR updates the mongo-php-library submodule to trigger staging.
JIRA: https://jira.mongodb.org/browse/DOCSP-36027
Staging: https://preview-mongodbnorareidy.gatsbyjs.io/php-library/DOCSP-36027/
> DOCSP-36027: Shorten class headings

- .gitmodules
JIRA - https://jira.mongodb.org/browse/DOCSP-37038
Staging - https://preview-mongodbnorareidy.gatsbyjs.io/php-library/DOCSP-37038-backport/
> DOCSP-37038: Fix links backport

- .gitmodules
JIRA - https://jira.mongodb.org/browse/DOCSP-36027
Staging - https://preview-mongodbnorareidy.gatsbyjs.io/php-library/DOCSP-36027-backport/
> DOCSP-36027: Fix headings backport

- .gitmodules
JIRA - https://jira.mongodb.org/browse/DOCSP-36627
Staging - https://preview-mongodbnorareidy.gatsbyjs.io/php-library/DOCSP-36627-more-slash-fixes/
> DOCSP-36627: More backslash fixes (staging)

- .gitmodules
JIRA - https://jira.mongodb.org/browse/DOCSP-36627
Staging - https://preview-mongodbnorareidy.gatsbyjs.io/php-library/DOCSP-36627-staging/
> DOCSP-36627: Fix backslashes (staging)

- .gitmodules
JIRA - https://jira.mongodb.org/browse/DOCSP-36627
Staging - https://preview-mongodbnorareidy.gatsbyjs.io/php-library/DOCSP-36627-v1.17/
> DOCSP-36627: Fix backslashes 1.17 (staging)

- config/redirects
JIRA - https://jira.mongodb.org/browse/DOCSP-38108
Note: no changes to snooty.toml needed; no compatiblity tables in these docs
> DOCSP-38108: 1.18 updates

- .gitmodules
JIRA - https://jira.mongodb.org/browse/DOCSP-37027
Staging - https://preview-mongodbnorareidy.gatsbyjs.io/php-library/DOCSP-37027-build-errors/
Build log - https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=663a527fb67dbf804ac387bb
> DOCSP-37027: Fix build errors

- .gitmodules
> DOCSP-37027: v1.17 build fixes

- .gitmodules
Staging - https://preview-mongodbnorareidy.gatsbyjs.io/php-library/DOCSP-37027-more-fixes-1.18/
> DOCSP-37027: Additional build fixes 1.18

- .gitmodules
Fixes the broken link in row 120 [here.](https://docs.google.com/spreadsheets/d/1kQ4epk1M-ZW-Gby5YGfJmJCTLIGH5tauqFItcRLBqmg/edit#gid=566175930)
Staging: https://preview-mongodbmongokart.gatsbyjs.io/php-library/docsp-38371-broken-links/tutorial/decimal128/
> DOCSP-38371 - Broken link

- config/redirects
Updating redirects for new version
[Jira](https://jira.mongodb.org/browse/DOCSP-39496)
> Update redirects for v1.19

- .gitmodules
Jira: https://jira.mongodb.org/browse/DOCSP-38371 (spreadsheet rows 113 and 119 only)
Staging:
- [Stable API](https://preview-mongodbmongokart.gatsbyjs.io/php-library/docsp-38371-more-links/reference/method/MongoDBClient__construct/)
- [Collations](https://preview-mongodbmongokart.gatsbyjs.io/php-library/docsp-38371-more-links/tutorial/collation/)
> DOCSP-38371 - v1.16 broken links

- source/includes/extracts-watch-option.yaml
- source/reference/method/MongoDBClient__construct.txt
- source/reference/method/MongoDBCollection-drop.txt
- source/reference/method/MongoDBCollection-mapReduce.txt
- source/reference/method/MongoDBDatabase-createCollection.txt
- source/reference/method/MongoDBDatabase-dropCollection.txt
Removed nested components according to [this doc](https://docs.google.com/document/d/1yMbng-EPOQ82bAzBTC2VJwIvsUBOSCJh21cGbDoe1a8/edit#heading=h.8t0xo8i29om4)
JIRA - https://jira.mongodb.org/browse/DOCSP-42966
Staging:
- https://preview-mongodbmongokart.gatsbyjs.io/php-library/docsp-42966-nested-components/reference/method/MongoDBClient__construct/
- https://preview-mongodbmongokart.gatsbyjs.io/php-library/docsp-42966-nested-components/reference/method/MongoDBClient-watch/
- https://preview-mongodbmongokart.gatsbyjs.io/php-library/docsp-42966-nested-components/reference/method/MongoDBCollection-drop/
- https://preview-mongodbmongokart.gatsbyjs.io/php-library/docsp-42966-nested-components/referen …
> DOCSP-42966 - Remove nested components

- config/redirects
- snooty.toml
JIRA - <https://jira.mongodb.org/browse/DOCSP-43819>
Staging - https://deploy-preview-155--docs-php-library.netlify.app/whats-new/#std-label-php-lib-version-1.20
> DOCSP-43819: php 1.20 release

- build.sh
- netlify.toml
- snooty.toml
JIRA - <https://jira.mongodb.org/browse/DOCSP-43977>
Staging - https://deploy-preview-160--docs-php-library.netlify.app/
> DOCSP-43977: eol v1.16

- source/whats-new.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-44298>
Staging - <https://deploy-preview-166--docs-php-library.netlify.app/whats-new/#std-label-php-lib-version-1.17>
> (DOCSP-44298) Removed EOL'd v1.16 and earlier. (#165)

- source/includes/databases-collections/databases-collections.php
- source/includes/databases-collections/time-series.php
- source/includes/read/cursor.php
- source/indexes/index-mgmt.txt
- source/reference/method/MongoDBClient-dropDatabase.txt
- source/reference/method/MongoDBCollection-drop.txt
- source/reference/method/MongoDBCollection-dropIndex.txt
- source/reference/method/MongoDBCollection-dropIndexes.txt
- source/reference/method/MongoDBCollection-dropSearchIndex.txt
- source/reference/method/MongoDBCollection-rename.txt
- source/reference/method/MongoDBDatabase-createCollection.txt
- source/reference/method/MongoDBDatabase-createEncryptedCollection.txt
- source/reference/method/MongoDBDatabase-drop.txt
- source/reference/method/MongoDBDatabase-dropCollection.txt
- source/reference/method/MongoDBDatabase-renameCollection.txt
- source/upgrade.txt
- source/whats-new.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-44002>
Staging:
[whats new](https://deploy-preview-170--docs-php-library.netlify.app/whats-new/#what-s-new-in-2.0)
[upgrade guide](https://deploy-preview-170--docs-php-library.netlify.app/upgrade/#version-2.0-breaking-changes)
[sample API method change](https://deploy-preview-170--docs-php-library.netlify.app/reference/method/MongoDBDatabase-drop/)
> DOCSP-44002: v2 void return types

- source/reference/method/MongoDBDatabase-createCollection.txt
- source/whats-new.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-44239>
Staging - https://deploy-preview-173--docs-php-library.netlify.app/whats-new/#std-label-php-lib-version-2.0
> DOCSP-44239: v2 remove flags option

- source/read/distinct.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-45139>
Staging - <https://deploy-preview-181--docs-php-library.netlify.app/read/distinct/>
> DOCSP-45139: Add Hint option for Distinct operation

- source/reference/method/MongoDBCollection-listIndexes.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-46718>
Staging - <https://deploy-preview-192--docs-php-library.netlify.app/reference/method/MongoDBCollection-listIndexes/#see-also>
> DOCSP-46718 Enumerting Collections Link 404

- source/write/transaction.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-45878
Staging - https://deploy-preview-204--docs-php-library.netlify.app/write/transaction/#transaction-example
> DOCSP-45878: Transactions parallelism note

- source/index.txt
- source/read.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-48025>
Staging - <https://deploy-preview-218--docs-php-library.netlify.app/read/>
> [PHP] Remove "MongoDB" from page title

- source/index.txt
- source/read.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-48025>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/NNNNN/>
> [PHP] Backport title fix to v1.21

- source/index.txt
- source/read.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-48025>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/NNNNN/>
> [PHP] Backport title fix to v2.0

- .github/pull_request_template.md
- .github/workflows/add-netlify-links.yml
JIRA - <https://jira.mongodb.org/browse/DOCSP-48771>
> DOCSP-48771 add netlify links

- source/connect/connection-targets.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-48761>
https://deploy-preview-237--docs-php-library.netlify.app/connect/connection-targets/#initialization
> DOCSP-48761: docker note

- source/get-started.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-48718>
<li><a href=https://deploy-preview-247--docs-php-library.netlify.app/get-started>get-started</a></li>
> DOCSP-48718-update-credentials

- source/get-started.txt
* update username and password
* misspelling
(cherry picked from commit 7bc5a55ec4dd501dce23d632b12c3f997e152f03)
JIRA - <https://jira.mongodb.org/browse/DOCSP-NNNNN>
<li><a href=https://deploy-preview-248--docs-php-library.netlify.app/get-started>get-started</a></li>
> DOCSP-48718-update-credentials (#247)

- composer/composer.json
- config/redirects
- snooty.toml
- source/includes/extracts-bulkwriteexception.yaml
- source/includes/extracts-error.yaml
- source/includes/language-compatibility-table-php.rst
- source/includes/mongodb-compatibility-table-php.rst
- source/includes/write/bulk-write.php
- source/reference.txt
- source/reference/class/MongoDBBulkWriteCommandResult.txt
- source/reference/class/MongoDBBulkWriteResult.txt
- source/reference/class/MongoDBClient.txt
- source/reference/class/MongoDBClientBulkWrite.txt
- source/reference/method/MongoDBClient-bulkWrite.txt
- source/reference/method/MongoDBClientBulkWrite-createWithCollection.txt
- source/reference/method/MongoDBClientBulkWrite-deleteMany.txt
- source/reference/method/MongoDBClientBulkWrite-deleteOne.txt
- source/reference/method/MongoDBClientBulkWrite-insertOne.txt
- source/reference/method/MongoDBClientBulkWrite-replaceOne.txt
- source/reference/method/MongoDBClientBulkWrite-updateMany.txt
- source/reference/method/MongoDBClientBulkWrite-updateOne.txt
- source/reference/method/MongoDBClientBulkWrite-withCollection.txt
- source/reference/method/MongoDBCollection-bulkWrite.txt
- source/reference/method/MongoDBCollection-insertMany.txt
- source/reference/result-classes.txt
- source/whats-new.txt
- source/write/bulk-write.txt
- source/write/replace.txt
- source/write/transaction.txt
- source/write/update.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-50294>
<li><a href=https://deploy-preview-256--docs-php-library.netlify.app/reference/class/MongoDBBulkWriteCommandResult>reference/class/MongoDBBulkWriteCommandResult</a></li><li><a href=https://deploy-preview-256--docs-php-library.netlify.app/reference/class/MongoDBClientBulkWrite>reference/class/MongoDBClientBulkWrite</a></li><li><a href=https://deploy-preview-256--docs-php-library.netlify.app/reference/method/MongoDBClient-bulkWrite>reference/method/MongoDBClient-bulkWrite</a></li><li><a href=https://deploy-preview-256--docs-php-library.netlify.app/reference/method/MongoDBClientBulkWrite-createWithCollection>reference/method/MongoDBClientBulkWrit …
> DOCSP-50294: V2.1 Release

- source/crud/transaction.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-47060
<li><a href=https://deploy-preview-261--docs-php-library.netlify.app/crud/transaction>crud/transaction</a></li>
> DOCSP-47060: Causal consistency

- snooty.toml
- source/includes/authentication.php
- source/security/authentication.txt
- source/security/authentication/aws-iam.txt
- source/security/authentication/scram.txt
- source/security/authentication/x509.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-50222
<li><a href=https://deploy-preview-266--docs-php-library.netlify.app/security/authentication/aws-iam>security/authentication/aws-iam</a></li><li><a href=https://deploy-preview-266--docs-php-library.netlify.app/security/authentication/scram>security/authentication/scram</a></li><li><a href=https://deploy-preview-266--docs-php-library.netlify.app/security/authentication/x509>security/authentication/x509</a></li><li><a href=https://deploy-preview-266--docs-php-library.netlify.app/security/authentication>security/authentication</a></li>
> DOCSP-50222: Reorganize auth pages

- source/connect/client.txt
- source/includes/connect/client.php
JIRA - https://jira.mongodb.org/browse/DOCSP-47072
<li><a href=https://deploy-preview-273--docs-php-library.netlify.app/connect/client>connect/client</a></li>
> DOCSP-47072: Client parameters
